language: python

jobs:
  include:
    - name: "Python on Linux"
      python:  # this works for Linux but is ignored on macOS or Windows
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
        - "3.8-dev"
        - "nightly"
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip install -r requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then pip install --user -r requirements.txt; fi

# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  - python3 setup.py build_ext --inplace || python setup.py build_ext --inplace
  - python3 setup.py install || python setup.py install
  - python3 compile_tests.py build_ext --inplace || python compile_tests.py build_ext --inplace
  - pytest