language: python
dist: xenial
os: linux
cache: pip

jobs:
  include:
    - name: "Python 3.6 on Linux"
      python:  # this works for Linux but is ignored on macOS or Windows
        - "3.6"
    - name: "Python 3.7 on Linux"
      python:
        - "3.7"
    - name: "Python 3.8 on Linux"
      python:
        - "3.8"
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      env:
        - PATH=/Users/travis/Library/Python/3.7/bin:$PATH
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Users/travis/AppData/Roaming/Python/Python38/Scripts:/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  # Linux doesn't support installing packages for only the user since it is run in a venv.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip install -r requirements.txt; else pip install --user -r requirements.txt; fi

before_script:
  - python3 setup.py build_ext --inplace || python setup.py build_ext --inplace
  - python3 setup.py install || python setup.py install
  - python3 compile_tests.py build_ext --inplace || python compile_tests.py build_ext --inplace

# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  - coverage run -m pytest tests/

after_success:
  bash <(curl -s https://codecov.io/bash)